# Generated by Django 3.0.4 on 2020-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
