# Generated by Django 3.0.4 on 2020-09-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200908_0730'),
        ('users', '0002_user_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendGroups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.TextField(blank=True, default=None, max_length=300),
        ),
    ]
