# Generated by Django 3.0.4 on 2020-09-07 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200908_0730'),
        ('todos', '0002_auto_20200903_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.Subject'),
        ),
    ]
