# Generated by Django 3.0.4 on 2020-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20200922_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todogroup',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todogroup',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
