# Generated by Django 3.0.4 on 2020-09-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TimeStampModel')),
                ('photo', models.ImageField(blank=True, upload_to='groups')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(default=1)),
            ],
            bases=('core.timestampmodel',),
        ),
    ]
