# Generated by Django 3.0.4 on 2020-09-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200902_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TimeStampModel')),
                ('photo', models.ImageField(blank=True, upload_to='groups')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('discription', models.TextField()),
                ('time', models.IntegerField()),
            ],
            bases=('core.timestampmodel',),
        ),
    ]
