# Generated by Django 3.0.4 on 2020-09-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200903_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
